### ISSUE TITLE
PDOException: SQLSTATE[42000]

### ISSUE THREAD

**Issue by ajcsmarty** [jimwins/scat#5]
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes in C:\xampp\htdocs\scat-master\vendor\robmorgan\phinx\src\Phinx\Db\Adapter\PdoAdapter.php:167

error on Migration command running

$ vendor/bin/phinx migrate
Phinx by CakePHP - https://phinx.org. 0.10.8

using config file .\phinx.yml
using config parser yaml
using migration paths
 - C:\xampp\htdocs\Road&story\scat-master\db\migrations
using seed paths
warning no environment specified, defaulting to: db
using adapter mysql
using database scat_db

 == 20190525052546 InitialSetup: migrating
PDOException: SQLSTATE[42000]: and so on error

**Comment by jimwins** [comment]
What version of MySQL are you using?

**Comment by ajcsmarty** [comment]
Apache/2.4.38, PHP/7.3.3, phpmyadmin 4.8.5, Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407

**Comment by jimwins** [comment]
Scat requires MySQL 8, this is now documented in the README.
